### ISSUE TITLE
Unclear origins suggestion

### ISSUE THREAD

**Issue by FX-Wood** [silentdigit/rpi-msmtp-setup#1]
Hey! I'm configuring unattended-upgrades on my raspberry pi and came across this while I was getting set up. This is super helpful. Thank you for making it.

One part of this gist that is either a typo or is just going over my head is here: 

> The following two lines should be the only uncommented lines in the `Origins-Pattern` section:
> ```
> "origin=Debian,codename=${distro_codename}-updates";
> "origin=Debian,codename=${distro_codename},label=Debian";
> "origin=Debian,codename=${distro_codename},label=Debian-Security";
> "origin=Raspbian,codename=${distro_codename},label=Raspbian";
> "origin=Raspberry Pi Foundation,codename=${distro_codename},label=Raspberry Pi Foundation";
> "origin=Syncthing,codename=debian,label=Syncthing";
> ```

The text says that only two lines should be uncommented, but there are 6 lines there. Here is what the default config has for this section (for reference):

```
Unattended-Upgrade::Origins-Pattern {
        // Codename based matching:
        // This will follow the migration of a release through different
        // archives (e.g. from testing to stable and later oldstable).
        // Software will be the latest available for the named release,
        // but the Debian release itself will not be automatically upgraded.
//      "origin=Debian,codename=${distro_codename}-updates";
//      "origin=Debian,codename=${distro_codename}-proposed-updates";
        "origin=Debian,codename=${distro_codename},label=Debian";
        "origin=Debian,codename=${distro_codename},label=Debian-Security";

        // Archive or Suite based matching:
        // Note that this will silently match a different release after
        // migration to the specified archive (e.g. testing becomes the
        // new stable).
//      "o=Debian,a=stable";
//      "o=Debian,a=stable-updates";
//      "o=Debian,a=proposed-updates";
//      "o=Debian Backports,a=${distro_codename}-backports,l=Debian Backports";
};
```

What I did is just use the 6 lines you suggested, I'm hoping that's what you meant. Thank you!

**Comment by maksimstojkovic** [comment]
Hi @FX-Wood!

Yes you are correct, I had previously modified this document based on some software I was testing, but as you've identified, I had not updated the line count.

The following lines should be used to maintain security updates, based on my understanding:

```
"origin=Debian,codename=${distro_codename},label=Debian";
"origin=Debian,codename=${distro_codename},label=Debian-Security";
"origin=Raspbian,codename=${distro_codename},label=Raspbian";
"origin=Raspberry Pi Foundation,codename=${distro_codename},label=Raspberry Pi Foundation";
```

These may be appropriate for hobby related projects on a RPi, but please check other sources for any other lines that should be included if you are working on a project exposed to the internet, or a critical system.
